// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DBContextFromSQLDB.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DBContextFromSQLDB.Models
{
    public partial interface ITestContextProcedures
    {
        Task<List<GetSomeDataResult>> GetSomeDataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
