// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBContextFromSQLDB.Models;

public partial class SomeTable
{
    public int Id { get; set; }

    public string Data { get; set; }
}