// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DBContextFromSQLDB.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DBContextFromSQLDB.Models
{
    public partial class TestContext
    {
        private ITestContextProcedures _procedures;

        public virtual ITestContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TestContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITestContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetSomeDataResult>().HasNoKey().ToView(null);
        }
    }

    public partial class TestContextProcedures : ITestContextProcedures
    {
        private readonly TestContext _context;

        public TestContextProcedures(TestContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetSomeDataResult>> GetSomeDataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetSomeDataResult>("EXEC @returnValue = [dbo].[GetSomeData]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
