// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClassLibrary1.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1.Models
{
    public partial class Database1Context
    {
        private IDatabase1ContextProcedures _procedures;

        public virtual IDatabase1ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new Database1ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDatabase1ContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetSomeDataResult>().HasNoKey().ToView(null);
        }
    }

    public partial class Database1ContextProcedures : IDatabase1ContextProcedures
    {
        private readonly Database1Context _context;

        public Database1ContextProcedures(Database1Context context)
        {
            _context = context;
        }

        public virtual async Task<List<GetSomeDataResult>> GetSomeDataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = returnValue?._value,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetSomeDataResult>("EXEC @returnValue = [dbo].[GetSomeData]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
